### ISSUE TITLE
crates.io ownership

### ISSUE THREAD

**Issue by icewind1991** [emosenkis/esp8266-hal#1]
Hello, with the [work on porting rust to esp32/esp8266](https://github.com/MabezDev/rust-xtensa) I've been working on getting it things to run on esp8266[[1]][[2]] and are currently working on a [esp8266-hal](https://github.com/icewind1991/esp8266-hal) implementation.

Since this project seems dead (and the mrustc based approach a dead end with the xtensa rust port), I would like to request ownership of the crates.io name for the esp8266 crate to publish my work under.

[1]: https://github.com/icewind1991/esp8266
[2]: https://github.com/icewind1991/xtensa-rust-quickstart/tree/esp8266

**Comment by emosenkis** [comment]
I'd be happy to in principle but since your project is so new, I'd like to wait a bit to ensure that it actually gains traction. Why don't you ping me when you reach the point where your implementation is ready to be used by others?

**Comment by icewind1991** [comment]
Fair enough

**Comment by MabezDev** [comment]
First off, I'd like to thank you for your esp mrustc work and projects, they inspired me to create https://github.com/esp-rs originally!

This repo supports three embedded HAL traits:

- `digital::InputPin`

- `digital::OutputPin`

- `digital::StatefulOutputPin`

Where as the current implementation in https://github.com/esp-rs/esp8266-hal supports those and more, specifically uarts and timers:

- Timer Traits: `embedded_hal::timer::{Cancel, CountDown, Periodic}`
- Serial Traits: `embedded_hal::serial::{Read, Write}`
- GPIO Traits: `embedded_hal::digital::v2::{toggleable, InputPin, OutputPin, StatefulOutputPin}`

I would argue that this implementation is fit to be used by others as it surpasses the functionality in this repo. What do you think? Do you have a minimum set of required features you'd like to see before transfering?

**Comment by emosenkis** [comment]
Hi, @MabezDev. I'm glad someone got something out of all that tinkering!

I'm glad that the new crate is coming along nicely. I don't have a minimum set of features, I just want to see that it becomes a library usable by others and therefore worth distributing on crates.io - as of now, my hesitations are:
- only one contributor
- no commits since March
- depends on esp8266 crate, which is on crates.io but the GitHub repo for it is missing the actual Rust source files
- uses path-based dependency on esp8266 crate instead of crates.io

**Comment by icewind1991** [comment]
I've bumbed the `esp8266` crate so the `esp8266-hal` can now depend on a the crates.io version

> depends on esp8266 crate, which is on crates.io but the GitHub repo for it is missing the actual Rust source files

the rust source files for that crate are generated from the svd files in the repo

**Comment by emosenkis** [comment]
Invitation sent
